/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import com.gym.dao.ChiTietDungCuDAO;
import com.gym.dao.ChiTietGoiTapDAO;
import com.gym.dao.DonHangDAO;
import com.gym.dao.DungCuDAO;
import com.gym.dao.GoiTapDAO;
import com.gym.dao.KhachHangDAO;
import com.gym.util.MsgBox;
import com.gym.dao.NhanVienDAO;
import com.gym.entity.ChiTietDungCu;
import com.gym.entity.ChiTietGoiTap;
import com.gym.entity.DonHang;
import com.gym.entity.DungCu;
import com.gym.entity.GoiTap;
import com.gym.entity.KhachHang;
import com.gym.entity.NhanVien;
import com.gym.util.Auth;
import com.gym.util.XDate;
import com.gym.util.XImage;
import java.io.File;
import java.net.URL;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAVEN
 */
public class QuanLyDonHang extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
    public QuanLyDonHang() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaDH = new javax.swing.JTextField();
        txtNgayTao = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();
        txtMaKH = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDonHang = new javax.swing.JTable();
        btnDoi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTienNhan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTienThua = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JButton();
        btnTaoDon = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        rdoCho = new javax.swing.JRadioButton();
        rdoDaThanhToan = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlMuaGoiTap = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGoiTap = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblChiTietGoiTap = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSearchCTGT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtSearchGT = new javax.swing.JTextField();
        btnChonGoiTap = new javax.swing.JButton();
        pnlThuePT = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtSearchGT1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblGoiTap1 = new javax.swing.JTable();
        btnChonGoiTap1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtSearchCTGT1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblChiTietGoiTap1 = new javax.swing.JTable();
        pnlMuaDungCu = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtSearchDC = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDungCu = new javax.swing.JTable();
        btnChonDungCu = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblChiTietDungCu = new javax.swing.JTable();
        txtSearchCTDC = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnSua1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(153, 153, 255)), "Thông tin đơn hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Mã đơn hàng:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Ngày tạo:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Tổng tiền:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Mã khách hàng:");

        txtMaDH.setEditable(false);
        txtMaDH.setText("0");
        txtMaDH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(255, 153, 255), new java.awt.Color(153, 153, 255)));
        txtMaDH.setEnabled(false);

        txtNgayTao.setEditable(false);
        txtNgayTao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(255, 153, 255), new java.awt.Color(153, 153, 255)));
        txtNgayTao.setEnabled(false);

        txtTongTien.setEditable(false);
        txtTongTien.setText("0");
        txtTongTien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(255, 153, 255)));
        txtTongTien.setEnabled(false);

        txtMaKH.setEditable(false);
        txtMaKH.setText("KHÁCH VÃNG LAI");
        txtMaKH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(255, 153, 255)));
        txtMaKH.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtMaKHPropertyChange(evt);
            }
        });
        txtMaKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaKHKeyTyped(evt);
            }
        });

        tblDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MÃ ĐH", "MÃ NV", "MÃ KH", "NGÀY TẠO", "TRẠNG THÁI", "TỔNG TIỀN", "TIỀN NHẬN", "TIỀN THỪA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDonHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDonHang);
        if (tblDonHang.getColumnModel().getColumnCount() > 0) {
            tblDonHang.getColumnModel().getColumn(6).setHeaderValue("TIỀN NHẬN");
            tblDonHang.getColumnModel().getColumn(7).setHeaderValue("TIỀN THỪA");
        }

        btnDoi.setText("ĐỔI");
        btnDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Tiền nhận:");

        txtTienNhan.setText("0");
        txtTienNhan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(255, 153, 255)));
        txtTienNhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienNhanKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Tiền thừa:");

        txtTienThua.setEditable(false);
        txtTienThua.setText("0");
        txtTienThua.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(255, 153, 255)));
        txtTienThua.setEnabled(false);

        btnThanhToan.setText("THANH TOÁN");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnTaoDon.setText("TẠO ĐƠN");
        btnTaoDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoDonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Trạng thái:");

        buttonGroup1.add(rdoCho);
        rdoCho.setText("Chờ");

        buttonGroup1.add(rdoDaThanhToan);
        rdoDaThanhToan.setText("Đã thanh toán");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTienNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaDH, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTaoDon))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnThanhToan))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoCho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoDaThanhToan))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTaoDon))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDoi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTongTien)
                            .addComponent(jLabel5))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTienNhan)
                            .addComponent(jLabel8))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTienThua)
                            .addComponent(jLabel9))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(rdoCho)
                            .addComponent(rdoDaThanhToan))
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThanhToan)
                .addGap(8, 8, 8))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 900, 310));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 153, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(204, 204, 255)));

        tblGoiTap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MÃ GT", "TÊN GÓI", "GIÁ", "THỜI HẠN", "MÔ TẢ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGoiTap);

        tblChiTietGoiTap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MÃ GT", "MÃ ĐH", "SỐ LƯỢNG", "NGÀY ĐK", "NGÀY KT", "GIÁ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblChiTietGoiTap);
        if (tblChiTietGoiTap.getColumnModel().getColumnCount() > 0) {
            tblChiTietGoiTap.getColumnModel().getColumn(3).setHeaderValue("NGÀY ĐK");
            tblChiTietGoiTap.getColumnModel().getColumn(4).setHeaderValue("NGÀY KT");
        }

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("DANH SÁCH SẢN PHẨM");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("CHI TIẾT HÓA ĐƠN");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/icon/search.png"))); // NOI18N

        txtSearchCTGT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchCTGTKeyReleased(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/icon/search.png"))); // NOI18N

        txtSearchGT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchGTKeyReleased(evt);
            }
        });

        btnChonGoiTap.setText("Chọn");
        btnChonGoiTap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonGoiTapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMuaGoiTapLayout = new javax.swing.GroupLayout(pnlMuaGoiTap);
        pnlMuaGoiTap.setLayout(pnlMuaGoiTapLayout);
        pnlMuaGoiTapLayout.setHorizontalGroup(
            pnlMuaGoiTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMuaGoiTapLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlMuaGoiTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMuaGoiTapLayout.createSequentialGroup()
                        .addComponent(btnChonGoiTap)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMuaGoiTapLayout.createSequentialGroup()
                        .addGroup(pnlMuaGoiTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(pnlMuaGoiTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlMuaGoiTapLayout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSearchGT, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(pnlMuaGoiTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMuaGoiTapLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchCTGT, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addGap(23, 23, 23))))
        );
        pnlMuaGoiTapLayout.setVerticalGroup(
            pnlMuaGoiTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMuaGoiTapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMuaGoiTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMuaGoiTapLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlMuaGoiTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchGT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMuaGoiTapLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlMuaGoiTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchCTGT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChonGoiTap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mua gói tập", pnlMuaGoiTap);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("DANH SÁCH SẢN PHẨM");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/icon/search.png"))); // NOI18N

        txtSearchGT1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchGT1KeyReleased(evt);
            }
        });

        tblGoiTap1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MÃ GT", "TÊN GÓI", "GIÁ", "THỜI HẠN", "MÔ TẢ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblGoiTap1);

        btnChonGoiTap1.setText("Chọn");
        btnChonGoiTap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonGoiTap1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("CHI TIẾT HÓA ĐƠN");

        txtSearchCTGT1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchCTGT1KeyReleased(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/icon/search.png"))); // NOI18N

        tblChiTietGoiTap1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MÃ GT", "MÃ ĐH", "SỐ LƯỢNG", "NGÀY ĐK", "NGÀY KT", "GIÁ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblChiTietGoiTap1);

        javax.swing.GroupLayout pnlThuePTLayout = new javax.swing.GroupLayout(pnlThuePT);
        pnlThuePT.setLayout(pnlThuePTLayout);
        pnlThuePTLayout.setHorizontalGroup(
            pnlThuePTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThuePTLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlThuePTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThuePTLayout.createSequentialGroup()
                        .addComponent(btnChonGoiTap1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlThuePTLayout.createSequentialGroup()
                        .addGroup(pnlThuePTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(pnlThuePTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlThuePTLayout.createSequentialGroup()
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSearchGT1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(pnlThuePTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlThuePTLayout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchCTGT1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17))
                        .addGap(23, 23, 23))))
        );
        pnlThuePTLayout.setVerticalGroup(
            pnlThuePTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThuePTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThuePTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThuePTLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlThuePTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchGT1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThuePTLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlThuePTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchCTGT1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChonGoiTap1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thuê huấn luyện viên", pnlThuePT);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("DANH SÁCH SẢN PHẨM");

        txtSearchDC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchDCKeyReleased(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/icon/search.png"))); // NOI18N

        tblDungCu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MÃ DC", "TÊN DC", "GIÁ", "SỐ LƯỢNG", "HÌNH"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblDungCu);

        btnChonDungCu.setText("Chọn");
        btnChonDungCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonDungCuActionPerformed(evt);
            }
        });

        tblChiTietDungCu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ DC", "MÃ ĐH", "SỐ LƯỢNG", "GIÁ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tblChiTietDungCu);

        txtSearchCTDC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchCTDCKeyReleased(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/icon/search.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("CHI TIẾT HÓA ĐƠN");

        javax.swing.GroupLayout pnlMuaDungCuLayout = new javax.swing.GroupLayout(pnlMuaDungCu);
        pnlMuaDungCu.setLayout(pnlMuaDungCuLayout);
        pnlMuaDungCuLayout.setHorizontalGroup(
            pnlMuaDungCuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMuaDungCuLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlMuaDungCuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMuaDungCuLayout.createSequentialGroup()
                        .addComponent(btnChonDungCu)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMuaDungCuLayout.createSequentialGroup()
                        .addGroup(pnlMuaDungCuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(pnlMuaDungCuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlMuaDungCuLayout.createSequentialGroup()
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSearchDC, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(pnlMuaDungCuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMuaDungCuLayout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchCTDC, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel22))
                        .addGap(23, 23, 23))))
        );
        pnlMuaDungCuLayout.setVerticalGroup(
            pnlMuaDungCuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMuaDungCuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMuaDungCuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMuaDungCuLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlMuaDungCuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchDC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMuaDungCuLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlMuaDungCuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchCTDC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChonDungCu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mua dụng cụ", pnlMuaDungCu);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 900, 290));

        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        jPanel1.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel1.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        jPanel1.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 144, -1));

        btnReset.setText("Làm mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 144, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/icon/search.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 30, 30));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 460, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("QUẢN LÝ ĐƠN HÀNG");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 330, 50));

        btnSua1.setText("Sửa");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 144, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiActionPerformed
        doiKH();
    }//GEN-LAST:event_btnDoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        timKiemDH();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed

    }//GEN-LAST:event_btnSua1ActionPerformed

    private void btnTaoDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoDonActionPerformed
        createDH();
        btnDoi.setEnabled(true);
    }//GEN-LAST:event_btnTaoDonActionPerformed

    private void tblDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonHangMouseClicked
        if (evt.getClickCount() == 2) {
            this.rowDH = tblDonHang.getSelectedRow();
            this.edit();
            this.fillChiTietGoiTap();
            this.fillChiTietDungCu();
        }
    }//GEN-LAST:event_tblDonHangMouseClicked

    private void txtMaKHPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtMaKHPropertyChange

    }//GEN-LAST:event_txtMaKHPropertyChange

    private void txtMaKHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaKHKeyTyped

    }//GEN-LAST:event_txtMaKHKeyTyped

    private void txtSearchCTGTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchCTGTKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchCTGTKeyReleased

    private void txtSearchGTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchGTKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchGTKeyReleased

    private void btnChonGoiTapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonGoiTapActionPerformed
        themGT();
    }//GEN-LAST:event_btnChonGoiTapActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        thanhToan();
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void txtTienNhanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienNhanKeyReleased
        tinhTien();
    }//GEN-LAST:event_txtTienNhanKeyReleased

    private void txtSearchGT1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchGT1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchGT1KeyReleased

    private void btnChonGoiTap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonGoiTap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChonGoiTap1ActionPerformed

    private void txtSearchCTGT1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchCTGT1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchCTGT1KeyReleased

    private void txtSearchDCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchDCKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchDCKeyReleased

    private void btnChonDungCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonDungCuActionPerformed
        themDC();
    }//GEN-LAST:event_btnChonDungCuActionPerformed

    private void txtSearchCTDCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchCTDCKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchCTDCKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonDungCu;
    private javax.swing.JButton btnChonGoiTap;
    private javax.swing.JButton btnChonGoiTap1;
    private javax.swing.JButton btnDoi;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnTaoDon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlMuaDungCu;
    private javax.swing.JPanel pnlMuaGoiTap;
    private javax.swing.JPanel pnlThuePT;
    private javax.swing.JRadioButton rdoCho;
    private javax.swing.JRadioButton rdoDaThanhToan;
    private javax.swing.JTable tblChiTietDungCu;
    private javax.swing.JTable tblChiTietGoiTap;
    private javax.swing.JTable tblChiTietGoiTap1;
    private javax.swing.JTable tblDonHang;
    private javax.swing.JTable tblDungCu;
    private javax.swing.JTable tblGoiTap;
    private javax.swing.JTable tblGoiTap1;
    private javax.swing.JTextField txtMaDH;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearchCTDC;
    private javax.swing.JTextField txtSearchCTGT;
    private javax.swing.JTextField txtSearchCTGT1;
    private javax.swing.JTextField txtSearchDC;
    private javax.swing.JTextField txtSearchGT;
    private javax.swing.JTextField txtSearchGT1;
    private javax.swing.JTextField txtTienNhan;
    private javax.swing.JTextField txtTienThua;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

    private int rowDH = -1;
    private int rowGT = -1;

    DonHangDAO dhdao = new DonHangDAO();
    GoiTapDAO gtdao = new GoiTapDAO();
    DungCuDAO dcdao = new DungCuDAO();
    ChiTietGoiTapDAO ctgtdao = new ChiTietGoiTapDAO();
    ChiTietDungCuDAO ctdcdao = new ChiTietDungCuDAO();

    private void init() {
        this.fillTableDH();
        this.fillTableGT();
        this.fillTableDC();

        this.rowDH = -1;
        this.updateStatus();
        txtNgayTao.setText(XDate.toString(new Date(), "dd-MM-yyyy"));
    }

    void tinhTien() {
        try {
            double tienNhan = Double.parseDouble(txtTienNhan.getText());
            double tongTien = Double.parseDouble(txtTongTien.getText());
            txtTienThua.setText(String.valueOf(tienNhan - tongTien));
        } catch (Exception e) {

        }
    }

    void updateDH() {
        DonHang dh = getForm();
        try {
            dhdao.update(dh);
            fillTableDH();
        } catch (Exception e) {
            System.out.println(e);
            MsgBox.alert(this, "Lưu thất bại");
        }
    }

    void thanhToan() {
        if (Double.parseDouble(txtTienThua.getText()) < 0) {
            int choice = JOptionPane.showConfirmDialog(this, "Đơn này vẫn còn nợ tiền, bạn muốn tiếp tục ?", "Hệ thống quản lý phòng gym", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                rdoDaThanhToan.setSelected(true);
                updateDH();
                MsgBox.alert(this, "Thanh toán thành công!");
            }
        } else {
            rdoDaThanhToan.setSelected(true);
            updateDH();
            MsgBox.alert(this, "Thanh toán thành công!");
        }
    }

    void fillTableDH() {
        DefaultTableModel model = (DefaultTableModel) tblDonHang.getModel();
        model.setRowCount(0);
        try {
            String keyword = txtSearch.getText();
            List<DonHang> list = dhdao.selectByKeyword(keyword); //đọc dữ liệu từ CSDL
            for (DonHang dh : list) {
                Object[] row = {dh.getMadh(), dh.getManv(), dh.getMakh(), dh.getNgayTao(),
                    dh.isTrangThai() ? "Đã thanh toán" : "Chờ", dh.getTongTien(),
                    dh.getTienNhan(), dh.getTienThua()};
                model.addRow(row); //thêm từng hàng vào JTable
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            System.out.println(e);
        }
    }

    DonHang getForm() {
        DonHang dh = new DonHang();
        dh.setMadh(Integer.parseInt(txtMaDH.getText()));
        dh.setManv(Auth.user.getMaNV());
        dh.setMakh(txtMaKH.getText());
        dh.setNgayTao(XDate.toDate(txtNgayTao.getText(), "dd-MM-yyyy"));
        dh.setTrangThai(rdoDaThanhToan.isSelected());
        dh.setTongTien(Double.parseDouble(txtTongTien.getText()));
        dh.setTienNhan(Double.parseDouble(txtTienNhan.getText()));
        dh.setTienThua(Double.parseDouble(txtTienThua.getText()));
        return dh;
    }

    void setForm(DonHang dh) {
        txtMaDH.setText(String.valueOf(dh.getMadh()));
        txtMaKH.setText(dh.getMakh());
        txtNgayTao.setText(XDate.toString(dh.getNgayTao(), "dd-MM-yyyy"));
        rdoCho.setSelected(!dh.isTrangThai());
        rdoDaThanhToan.setSelected(dh.isTrangThai());
        txtTongTien.setText(String.valueOf(dh.getTongTien()));
        txtTienNhan.setText(String.valueOf(dh.getTienNhan()));
        txtTienThua.setText(String.valueOf(dh.getTienThua()));
    }

    void updateStatus() {
        boolean edit = (this.rowDH >= 0);
        boolean first = (this.rowDH == 0);
        boolean last = (this.rowDH == tblDonHang.getRowCount() - 1);

        //Trạng thái form
        txtNgayTao.setEditable(!edit);
        btnDoi.setEnabled(edit);
        btnXoa.setEnabled(edit);
        //Trạng thái điều hướng
        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit);
        btnNext.setEnabled(edit);
        btnLast.setEnabled(edit && !last);
    }

    void clearForm() {
        DonHang dh = new DonHang();
        this.setForm(dh);
        this.rowDH = -1;
        tblGoiTap.clearSelection();
        tblDungCu.clearSelection();
        updateStatus();
    }

    void edit() {
        int madh = (int) tblDonHang.getValueAt(this.rowDH, 0);
        DonHang dh = dhdao.selectById(String.valueOf(madh));
//        ChiTietGoiTap ctgt = ctgtdao.selectByMaDH(String.valueOf(madh));
        this.setForm(dh);
//        this.setFormCTGT();
        this.updateStatus();
    }

    void createDH() {
        rdoCho.setSelected(true);
        DonHang dh = getForm();
        try {
            dhdao.createDH(dh);
            this.fillTableDH();
            this.clearForm();
            MsgBox.alert(this, "Tạo đơn mới thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Tạo đơn mới thất bại!");
            System.out.println(e);
        }

    }

    void delete() {
        String madh = txtMaDH.getText();
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền được xóa!");
        } else {
            if (MsgBox.confirm(this, "Bạn có thực sự muốn xóa đơn hàng này ?")) {
                try {
                    dhdao.delete(madh);
                    this.fillTableDH();
                    this.clearForm();
                    MsgBox.alert(this, "Xóa đơn hàng thành công!");
                } catch (Exception e) {
                    MsgBox.alert(this, "Xóa đơn hàng thất bại");
                    System.out.println(e);
                }
            }
        }
    }

    void first() {
        this.rowDH = 0;
        tblDonHang.setRowSelectionInterval(rowDH, rowDH);
        this.edit();
        System.out.println(rowDH);
    }

    void next() {
        if (this.rowDH < tblDonHang.getRowCount() - 1) {
            this.rowDH++;
            this.edit();
            tblDonHang.setRowSelectionInterval(rowDH, rowDH);
        } else {
            this.rowDH = 0;
            this.edit();
            tblDonHang.setRowSelectionInterval(rowDH, rowDH);
        }
        System.out.println(rowDH);
    }

    void prev() {
        if (this.rowDH > 0) {
            this.rowDH--;
            this.edit();
            tblDonHang.setRowSelectionInterval(rowDH, rowDH);
        } else {
            this.rowDH = tblDonHang.getRowCount() - 1;
            this.edit();
            tblDonHang.setRowSelectionInterval(rowDH, rowDH);
        }
        System.out.println(rowDH);
    }

    void last() {
        this.rowDH = tblDonHang.getRowCount() - 1;
        this.edit();
        tblDonHang.setRowSelectionInterval(rowDH, rowDH);
        System.out.println(rowDH);
    }

    void timKiemDH() {
        this.fillTableDH();
        this.clearForm();
        this.rowDH = -1;
        updateStatus();
    }

    void doiKH() {
        DoiKHJDialog dialog = new DoiKHJDialog();
        dialog.setModal(true);  // để JPanel chờ đến khi JDialog đóng
        dialog.setVisible(true);
        // Khi JDialog đóng, lấy dữ liệu đã chọn
        String makh = dialog.getSelectedData();
        // Đặt dữ liệu vào txtMaKH
        txtMaKH.setText(makh);
        if (!txtMaKH.getText().isEmpty()) {
            updateDH();
        } else {
            MsgBox.alert(this, "vui lòng chọn khách hàng!");
        }
    }

    //TAB MUA GÓI TẬP
    void fillTableGT() {
        DefaultTableModel model = (DefaultTableModel) tblGoiTap.getModel();
        model.setRowCount(0);
        try {
            String keyword = txtSearchGT.getText();
            List<GoiTap> list = gtdao.selectByKeyword(keyword); //đọc dữ liệu từ CSDL
            for (GoiTap gt : list) {
                Object[] row = {gt.getMaGT(), gt.getTenGoi(), gt.getGia(), gt.getThoiHan(),
                    gt.getMoTa()};
                model.addRow(row); //thêm từng hàng vào JTable
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            System.out.println(e);
        }
    }

    private int valueGT = 0;

    void themGT() {
        try {
            String get = JOptionPane.showInputDialog("Nhập vào số lượng: ");
            valueGT = Integer.parseInt(get);
            createCTGT();
        } catch (Exception e) {
            System.out.println(e);
            MsgBox.alert(this, "Vui lòng nhập vào một số!");
        }
        //lấy dữ liệu của từng ô làm get form. vd: tblGoiTap.getValueAt(0,0) để lấy mã gt. 0,1 để lấy tên gói...
        //tạo dao rồi thêm vào bảng chi tiết bình thường
    }

    void fillChiTietGoiTap() {
        DefaultTableModel model = (DefaultTableModel) tblChiTietGoiTap.getModel();
        model.setRowCount(0);
        try {
            int keyword = (int) tblDonHang.getValueAt(tblDonHang.getSelectedRow(), 0);
            List<ChiTietGoiTap> list = ctgtdao.selectByMaDH_CTGT(keyword); //đọc dữ liệu từ CSDL
            for (ChiTietGoiTap ctgt : list) {
                Object[] row = {ctgt.getMadh(), ctgt.getMagt(), ctgt.getSoluong(), ctgt.getNgaydk(),
                    ctgt.getNgaykt(), ctgt.getGia()};
                model.addRow(row); //thêm từng hàng vào JTable
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            System.out.println(e);
        }
    }

    ChiTietGoiTap getFormSP_GT() {
        ChiTietGoiTap ctgt = new ChiTietGoiTap();
        ctgt.setMactgt(ABORT);
        ctgt.setMakh((String) tblDonHang.getValueAt(tblDonHang.getSelectedRow(), 2));
        ctgt.setMagt((String) tblGoiTap.getValueAt(tblGoiTap.getSelectedRow(), 0));
        ctgt.setMadh((int) tblDonHang.getValueAt(tblDonHang.getSelectedRow(), 0));
        ctgt.setNgaydk(new Date());
        if (tblChiTietGoiTap.getRowCount() == 0) {
            ctgt.setNgaykt(XDate.addDay(new Date(), valueGT * (int) tblGoiTap.getValueAt(tblGoiTap.getSelectedRow(), 3)));
        } else if (tblChiTietGoiTap.getRowCount() >= 1) {
            for (int i = 1; i <= tblChiTietGoiTap.getRowCount(); i++) {
                ctgt.setNgaykt(XDate.addDay((Date) tblChiTietGoiTap.getValueAt(i - 1, 4), valueGT * (int) tblGoiTap.getValueAt(tblGoiTap.getSelectedRow(), 3)));
            }
        }
        ctgt.setSoluong(valueGT);
        double gia = (double) tblGoiTap.getValueAt(tblGoiTap.getSelectedRow(), 2);
        ctgt.setGia(valueGT * gia);
        return ctgt;
    }
    
    private double tempGT = 0;
    void createCTGT() {    
        double tongGT = 0;
        ChiTietGoiTap ctgt = getFormSP_GT();
        try {
            ctgtdao.insert(ctgt);
            this.fillChiTietGoiTap();
            for (int i = 0; i < tblChiTietGoiTap.getRowCount(); i++) {
                tongGT = tongGT + (double) tblChiTietGoiTap.getValueAt(i, 5);
            }
            tempGT = tongGT;
//            if (Double.parseDouble(txtTongTien.getText()) == 0) {
//                txtTongTien.setText(String.valueOf(tongGT));
//            } else {
//                txtTongTien.setText(String.valueOf(tongGT + Double.parseDouble(txtTongTien.getText())));
//            }
            if(tblChiTietDungCu.getRowCount()==0){
                txtTongTien.setText(String.valueOf(tongGT));
            }
            else{
                txtTongTien.setText(String.valueOf(tongGT + tempDC));
            }
            updateDH();
            this.clearForm();
            MsgBox.alert(this, "Thêm sản phẩm vào đơn thành công!");
        } catch (Exception e) {
            System.out.println(e);
            MsgBox.alert(this, "Thêm sản phẩm vào đơn thất bại!");
        }
    }

    //TAB MUA DỤNG CỤ
    void fillTableDC() {
        DefaultTableModel model = (DefaultTableModel) tblDungCu.getModel();
        model.setRowCount(0);
        try {
            String keyword = txtSearchDC.getText();
            List<DungCu> list = dcdao.selectByKeyword(keyword); //đọc dữ liệu từ CSDL
            for (DungCu dc : list) {
                Object[] row = {dc.getMadc(), dc.getTendc(), dc.getGia(), dc.getSl(),
                    dc.getHinh()};
                model.addRow(row); //thêm từng hàng vào JTable
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            System.out.println(e);
        }

    }

    private int valueDC = 0;

    void themDC() {
        try {
            String get = JOptionPane.showInputDialog("Nhập vào số lượng: ");
            valueDC = Integer.parseInt(get);
            createCTDC();
        } catch (Exception e) {
            System.out.println(e);
            MsgBox.alert(this, "Vui lòng nhập vào một số!");
        }
    }

    void fillChiTietDungCu() {
        DefaultTableModel model = (DefaultTableModel) tblChiTietDungCu.getModel();
        model.setRowCount(0);
        try {
            int keyword = (int) tblDonHang.getValueAt(tblDonHang.getSelectedRow(), 0);
            List<ChiTietDungCu> list = ctdcdao.selectByMaDH_CTDC(keyword); //đọc dữ liệu từ CSDL
            for (ChiTietDungCu ctdc : list) {
                Object[] row = {ctdc.getMadc(), ctdc.getMadh(), ctdc.getSl(), ctdc.getGia()};
                model.addRow(row); //thêm từng hàng vào JTable
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            System.out.println(e);
        }
    }

    ChiTietDungCu getFormSP_DC() {
        ChiTietDungCu ctdc = new ChiTietDungCu();
        ctdc.setMactdc(ABORT);
        ctdc.setMadc((String) tblDungCu.getValueAt(tblDungCu.getSelectedRow(), 0));
        ctdc.setMadh((int) tblDonHang.getValueAt(tblDonHang.getSelectedRow(), 0));
        ctdc.setMakh((String) tblDonHang.getValueAt(tblDonHang.getSelectedRow(), 2));
        ctdc.setSl(valueDC);
        double gia = (double) tblDungCu.getValueAt(tblDungCu.getSelectedRow(), 2);
        ctdc.setGia(valueDC * gia);
        return ctdc;
    }
    
    private double tempDC = 0;
    void createCTDC() {
        double tongDC = 0;
        ChiTietDungCu ctdc = getFormSP_DC();
        try {
            ctdcdao.insert(ctdc);
            this.fillChiTietDungCu();
            for (int i = 0; i < tblChiTietDungCu.getRowCount(); i++) {
                tongDC = tongDC + (double) tblChiTietDungCu.getValueAt(i, 3);
            }
            tempDC = tongDC;
//            
            if(tblChiTietGoiTap.getRowCount()==0){
                txtTongTien.setText(String.valueOf(tongDC));
            }
            else{
                txtTongTien.setText(String.valueOf(tongDC + tempGT));
            }
            updateDH();
            this.clearForm();
            MsgBox.alert(this, "Thêm sản phẩm vào đơn thành công!");
        } catch (Exception e) {
            System.out.println(e);
            MsgBox.alert(this, "Thêm sản phẩm vào đơn thất bại!");
        }
    }

    
}
