/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.raven.form;

import com.gym.dao.NhanVienDAO;
import com.gym.entity.NhanVien;
import com.gym.util.Auth;
import com.gym.util.MsgBox;
import java.util.List;
import java.util.Properties;
import java.util.Random;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class QuenMatKhauTiepTheo extends javax.swing.JDialog {

    /**
     * Creates new form QuenMatKhau1
     */
    public QuenMatKhauTiepTheo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private String manv;

    public QuenMatKhauTiepTheo(String manv) {
        initComponents();
        this.manv = manv; // Lưu giá trị manv từ JPanel QuenMatKhau
        setLocationRelativeTo(null);
    }

    NhanVienDAO dao = new NhanVienDAO();
    private String otpStr; // Khai báo biến toàn cục
    private String email;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtXacNhanMatKhau = new javax.swing.JPasswordField();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        lblShowpass1 = new javax.swing.JLabel();
        lblHidepass1 = new javax.swing.JLabel();
        lblShowpass2 = new javax.swing.JLabel();
        lblHidepass2 = new javax.swing.JLabel();
        btnXacNhanDoiMK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUÊN MẬT KHẨU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 725, 56));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu mới:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Xác nhận mật khẩu:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        jPanel1.add(txtXacNhanMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 340, -1));

        txtMatKhauMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauMoiActionPerformed(evt);
            }
        });
        jPanel1.add(txtMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 340, -1));

        lblShowpass1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowpass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/icon/hide.png"))); // NOI18N
        lblShowpass1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblShowpass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowpass1MouseClicked(evt);
            }
        });
        jPanel1.add(lblShowpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 50, 40));

        lblHidepass1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHidepass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/icon/eye.png"))); // NOI18N
        lblHidepass1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHidepass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHidepass1MouseClicked(evt);
            }
        });
        jPanel1.add(lblHidepass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 50, 40));

        lblShowpass2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowpass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/icon/hide.png"))); // NOI18N
        lblShowpass2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblShowpass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowpass2MouseClicked(evt);
            }
        });
        jPanel1.add(lblShowpass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 50, 40));

        lblHidepass2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHidepass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/icon/eye.png"))); // NOI18N
        lblHidepass2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHidepass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHidepass2MouseClicked(evt);
            }
        });
        jPanel1.add(lblHidepass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 50, 40));

        btnXacNhanDoiMK.setText("Đổi mật khẩu");
        btnXacNhanDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanDoiMKActionPerformed(evt);
            }
        });
        jPanel1.add(btnXacNhanDoiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatKhauMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauMoiActionPerformed

    private void lblShowpass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowpass1MouseClicked
        lblShowpass1.setVisible(false);
        lblHidepass1.setVisible(true);
        txtMatKhauMoi.setEchoChar((char) 0);
    }//GEN-LAST:event_lblShowpass1MouseClicked

    private void lblHidepass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHidepass1MouseClicked
        lblShowpass1.setVisible(true);
        lblHidepass1.setVisible(false);
        txtMatKhauMoi.setEchoChar((char) 8226);
    }//GEN-LAST:event_lblHidepass1MouseClicked

    private void lblShowpass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowpass2MouseClicked
        lblShowpass2.setVisible(false);
        lblHidepass2.setVisible(true);
        txtXacNhanMatKhau.setEchoChar((char) 0);
    }//GEN-LAST:event_lblShowpass2MouseClicked

    private void lblHidepass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHidepass2MouseClicked
        lblShowpass2.setVisible(true);
        lblHidepass2.setVisible(false);
        txtXacNhanMatKhau.setEchoChar((char) 8226);
    }//GEN-LAST:event_lblHidepass2MouseClicked

    private void btnXacNhanDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanDoiMKActionPerformed
        QuenMatKhau qmk = new QuenMatKhau();
        String strMaNV = manv;
        String strMatKhauMoi = new String(txtMatKhauMoi.getPassword());
        String strMatKhauMoi2 = new String(txtXacNhanMatKhau.getPassword());

        List<NhanVien> list = dao.selectAll();

        NhanVien nv = dao.selectById(strMaNV);

        if (new String(txtMatKhauMoi.getPassword()).isEmpty()) {
            MsgBox.alert(this, "Chưa nhập mật khẩu mới!");
        } else if (!strMatKhauMoi.equals(strMatKhauMoi2)) {
            MsgBox.alert(this, "Xác nhận mật khẩu không đúng!");
        } else {
            int option = JOptionPane.showOptionDialog(this, "Bạn có chắc muốn đổi mật khẩu", "Xác nhận",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                    new Object[]{"Yes", "No"}, "No");

            if (option == JOptionPane.YES_OPTION) {
                for (NhanVien nv1 : list) {
                    if (strMaNV.equals(nv.getMaNV())) {
                        nv.setMatKhau(strMatKhauMoi);
                        dao.update(nv);
                    } else {
                        MsgBox.alert(this, "Đổi mật khẩu thất bại!");
                    }
                }
                MsgBox.alert(this, "Đổi mật khẩu thành công!");
                this.dispose();
                new DangNhap().setVisible(true);
            }
        }


    }//GEN-LAST:event_btnXacNhanDoiMKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauTiepTheo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauTiepTheo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauTiepTheo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauTiepTheo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMatKhauTiepTheo dialog = new QuenMatKhauTiepTheo();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhanDoiMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHidepass1;
    private javax.swing.JLabel lblHidepass2;
    private javax.swing.JLabel lblShowpass1;
    private javax.swing.JLabel lblShowpass2;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtXacNhanMatKhau;
    // End of variables declaration//GEN-END:variables
}
