/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gym.form;

import com.gym.dao.NhanVienDAO;
import com.gym.entity.NhanVien;
import com.gym.util.Auth;
import com.gym.util.MsgBox;
import java.util.List;
import java.util.Properties;
import java.util.Random;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class QuenMatKhau extends javax.swing.JDialog {

    /**
     * Creates new form QuenMatKhau1
     */
    public QuenMatKhau() {
        initComponents();
        setLocationRelativeTo(null);
    }

    NhanVienDAO dao = new NhanVienDAO();
    private String otpStr; // Khai báo biến toàn cục
    private String email;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaOTP = new javax.swing.JTextField();
        btnLayOTP = new javax.swing.JButton();
        btnTiepTucDoiMK = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUÊN MẬT KHẨU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 725, 56));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Xác nhận OTP:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));
        jPanel1.add(txtMaOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 340, -1));

        btnLayOTP.setText("Lấy mã OTP");
        btnLayOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayOTPActionPerformed(evt);
            }
        });
        jPanel1.add(btnLayOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        btnTiepTucDoiMK.setText("Tiếp tục");
        btnTiepTucDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiepTucDoiMKActionPerformed(evt);
            }
        });
        jPanel1.add(btnTiepTucDoiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Email:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 40, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 340, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLayOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayOTPActionPerformed
        // Cấu hình thông tin tài khoản email
        Properties p = new Properties();
        p.put("mail.smtp.auth", "true");
        p.put("mail.smtp.starttls.enable", "true");
        p.put("mail.smtp.host", "smtp.gmail.com");
        p.put("mail.smtp.port", "587");
        p.put("mail.smtp.socketFactory.port", "587");
        p.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        p.put("mail.smtp.ssl.protocols", "TLSv1.2");

        String accountName = "dinhlhpc05738@fpt.edu.vn";
        String accountPasWord = "hfknngueqzmwtljg";

        // Tạo một phiên làm việc mới để gửi email
        Session session = Session.getDefaultInstance(p, new Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(accountName, accountPasWord);
            }
        });

        try {
            // Tạo đối tượng MimeMessage để gửi email
            MimeMessage message = new MimeMessage(session);
            boolean found = false;
            // Lấy ra email của mã nhân viên nhập vào
            try {
                List<NhanVien> list = dao.selectAll();
                for (NhanVien nv : list) {
                    if (txtEmail.getText().equals(nv.getEmail())) {
                        email = nv.getEmail();
                        System.out.println(email);
                        found = true;
                        MsgBox.alert(this, "OTP đã được gửi tới mail!");
                        break;
                    } 
                }
                if(!found){
                    MsgBox.alert(this, "Không tìm thấy email tồn tại tương ứng với mã nhân viên\nhoặc nhân viên không tồn tại!");

                }

                message.setFrom(new InternetAddress(accountName));
                message.addRecipient(Message.RecipientType.TO, new InternetAddress(email));
                //dlehoang415@gmail.com

                // Tạo mã OTP ngẫu nhiên
                Random random = new Random();
                int otp = random.nextInt(900000) + 100000; // Tạo một số ngẫu nhiên có 6 chữ số
                otpStr = Integer.toString(otp); // Gán giá trị của số ngẫu nhiên cho biến otpStr

                // Thiết lập tiêu đề và nội dung email
                message.setSubject("Mã OTP của bạn");
                message.setText("Đây là mã OTP của bạn: " + otpStr);

                // Gửi email
                Transport.send(message);
                
            } catch (Exception e) {
            }
//            
            // Thiết lập thông tin người gửi và người nhận
        } catch (Exception mex) {

        }
    }//GEN-LAST:event_btnLayOTPActionPerformed

    private String emailnv;

    private void btnTiepTucDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiepTucDoiMKActionPerformed
        String strEmail = txtEmail.getText();
        emailnv = strEmail;
        boolean found = false;
        
        if(txtEmail.getText().equals("")){
            MsgBox.alert(this, "Vui lòng nhập email!");
            return;
        }

        String strOTP = txtMaOTP.getText();

        List<NhanVien> list = dao.selectAll();

        for (NhanVien nv : list) {
            if(txtEmail.getText().equals(nv.getEmail())){
                if (strOTP.equals(otpStr)) {
                    found = true;
                    this.dispose();
                    QuenMatKhauTiepTheo qmkTiepTheo = new QuenMatKhauTiepTheo(emailnv);
                    qmkTiepTheo.setVisible(true);
                } 
            }
        }
        if(!found){
            MsgBox.alert(this, "OTP sai! Vui lòng nhập lại!");
        }
    }//GEN-LAST:event_btnTiepTucDoiMKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMatKhau dialog = new QuenMatKhau();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLayOTP;
    private javax.swing.JButton btnTiepTucDoiMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaOTP;
    // End of variables declaration//GEN-END:variables
}
